### ISSUE TITLE
PCsolver module not found error

### ISSUE THREAD

**Issue by Srob240** [differint/differint#17]
I'm trying to use the PCsolver but no matter how I import differint or differint.differint, it gives me the same error of module not found.

**Comment by cooperhatfield** [comment]
Sorry! The namespace has been cleaned up now. You should be able to access the PCsolver function through the code:
```python
import differint as di
result = di.PCsolver(...)
```
Note that the PCsolver function has not yet been released onto pypi, so to get the most recent version of the package you will have to download the "work" branch from github, and install it with the command
```bash
pip install /path/to/differint/
```
