### ISSUE TITLE
Show singularities at endpoints

### ISSUE THREAD

**Issue by CheapMeow** [differint/differint#21]
I use this to test:

```python
import numpy as np
import differint.differint as df
import matplotlib.pyplot as plt

def f(t):
    return np.power(t, 3)

alpha = 0.6

t_1 = np.linspace(-1, 1, 100)
t_2 = np.linspace(0, 1, 100)
GL_1 = df.GL(alpha, f, -1, 1, 100)
GL_2 = df.GL(alpha, f, 0, 1, 100)

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.plot(t_1, GL_1, marker='o', markevery=5)
ax.plot(t_2, GL_2, marker='x', markevery=5)

plt.show()
```

And this is result. Obviously, 0.6 derivative of the function y = x^3 shouldn't be so low at endpoint. 

In particular, its fractional derivative should be 0 at zero, but if you give differint to sovle [0,1], it would be wrong at x = 0.

![image](https://user-images.githubusercontent.com/88229072/222075057-24c9bf25-9c33-457b-bebc-204dd859a8a6.png)

**Comment by cooperhatfield** [comment]
Hello @CheapMeow, the asymptotic behavior at the left endpoint is a side effect of how the Grunwald-Letnikov differintegral is implemented. Comparing to the result gained from the Riemann-Liouville differintegral and the expected results, we see that it much more accurate. 
![image](https://user-images.githubusercontent.com/47254427/223286956-360d43d8-94b8-4326-8ce5-642fc0aad91c.png)

These results were obtained using the following code:
```Python
import numpy as np
import differint.differint as df
import matplotlib.pyplot as plt

def f(t):
    return np.power(t, 3)
def neg_f(t):
    return f(-1 * t)


alpha = 0.6

t_2 = np.linspace(0, 1, 100)
GL_2 = df.GL(alpha, f, 0, 1, 100)

GL_2_rev = df.RL(alpha, f, 0, 1, 100)

expected = lambda t: 6/(df.Gamma(3-alpha+1)) * t ** (3 - alpha)


fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.plot(t_2, GL_2, label='GL')
ax.plot(t_2, GL_2_rev, marker='o', markevery=5, label='RL')
ax.plot(t_1, expected(t_1), label='expected')
ax.legend()

plt.show()
```
Another thing to point out, is that to conserve many of the properties one might expect from the fractional derivative of polynomials, the left endpoint should be kept to 0; I only included that case.
