### ISSUE TITLE
How to use this for fractional derivatives at a point?

### ISSUE THREAD

**Issue by shaunster0** [differint/differint#4]
hi, i’d just like an example of how to use this to get fractional derivatives. I want to get fractional derivatives of a Gaussian. Seems like the RL function doesn’t return this (at least the numbers it returns do not seem to be the fractional derivative at a point, maybe they’re the integral of it or something)

So how would I do this?

**Comment by snimpids** [comment]
The RL function is for calculating the RL derivative at every point on a function's domain. You pass in an array of function values and get an array of fractional derivatives back.

The 'RLpoint' function is for calculating the RL derivative at a specific point. You can pass in the point as the 'domain_end' parameter.

Please let me know how this goes!

**Comment by shaunster0** [comment]
Matt, thanks for your reply!! it’d be good if there was a few clear examples of how to use it for some common functions ... the numbers that I got for fractional derivatives of a Gaussian weren’t right, I guess I’m using it the wrong way. Is there RL function reliable?

So how would I use it to calculate the 0.5 order derivative of a Gaussian exp(-1/2 x^2) ?

**Comment by snimpids** [comment]
It looks like you've found an oversight in the code. I'll have to revisit this after I review Diethelm et al, since it's been a long time since I wrote this.

**Comment by shaunster0** [comment]
thanks Matt! It’d be great if u could do this, I can see fractional derivatives becoming very important to some applications in physics and computer science (particularly for Gaussian type functions).

**Comment by cooperhatfield** [comment]
I've compared the result given by your code snippet with the expected result given by 
![image](https://user-images.githubusercontent.com/47254427/202033996-b10a68a9-93b4-4a45-aead-6f0c55a404ff.png)
Note, this is the theoretical result when the left endpoint is 0. For exponential functions, generally a left endpoint of negative infinity is used. But in any case, this is a comparison of the results:
![image](https://user-images.githubusercontent.com/47254427/202035920-5563c710-f79f-495f-918b-e8d590df6b92.png)
In the case where the left endpoint decreases to -100, the result becomes
![image](https://user-images.githubusercontent.com/47254427/202036008-f11a4457-d9fb-4ae4-a35f-26b91d2b22c3.png)
Which is likely closer to what you're expecting.

**Comment by shaunster0** [comment]
thanks Cooper!

**Comment by shaunster0** [comment]
it’d be good if a couple examples of this usage could be given on the project main page, this would be confusing to a new user … ie. setting the endpoint correctly on some common function

**Comment by cooperhatfield** [comment]
Hi shaunster0, 
A github wiki page has been made for this repo [here](https://github.com/differint/differint/wiki,) please let me know if that is helpful, or what you think could be improved! 

And just a note WRT the wiki, the Caputo methods are only available on a branch currently, not on the main package.

**Comment by cooperhatfield** [comment]
Tomorrow I will update the readme with more examples though, you're right.

**Comment by shaunster0** [comment]
thanks, appreciate what ure doing here, this project needed a makeover … it was amazing to me that there was no good quality python library for fractional derivatives
